### ISSUE TITLE
Shall we move back to wazero?

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza-wasilibs#15]
According to the [wazerox repository](github.com/wasilibs/wazerox) all features have been merged upstream so I wonder if we should move back to wazero.

**Comment by anuraaga** [comment]
They're merged but not tagged yet will be switched after that

**Comment by jcchavezs** [comment]
Wonder if this is happening anytime soon @evacchi

**Comment by evacchi** [comment]
we're finalizing the optimizing compiler; it's likely it will happen in a few weeks. Maybe we'll also tag some -pre earlier.

**Comment by anuraaga** [comment]
Is it ok to close this issue? Releasing a new tag if go-re2 after the next wazero is definitely on my radar as general maintenance and otherwise it doesn't really have much to do with this repo I guess since it's a transitive dep.

**Comment by jcchavezs** [comment]
Totally, the main question was if we should move back.
